# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/dkri3c1"

[social.params]
icon = "brand-github"

[[social]]
identifier = "Instagram"
name = "Instagram"
url = "https://www.instagram.com/"

[social.params]
icon = "ig"
